### ISSUE TITLE
MyPage 부분 HTML 및 SCSS 적용

### ISSUE THREAD

**Issue by xogk1128** [Scapture/Scapture-Client#10]
### ⚠️Issue

- MyPage 페이지에서 구조를 분석하고 SCSS를 제작한 후 HTML에 적용한다.

### ✏️Task

- [x] 사용자 프로필 SCSS 작성 및 적용
- [x] 예약 내역 확인하기 부분 작성
- [x] 저장된 영상 부분 작성
- [x] 프로필 수정 페이지 작성
- [x] 예약 내역 확인하기 작성

### 🗓Next Task

- [ ] x
