### ISSUE TITLE
MyPage에서 Edit 페이지 편집 완료 후 업데이트 되지 않는 부분 수정

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#108]
### ⚠️Issue

- MyPage에서 Edit페이지에서 편집이 완료 된 후 업데이트 되지 않는 이미지 확인 및 점검

### ✏️Task

- [x] 일반 Link가 아닌 useNavigate로 전환
- [x] 수정 후 MyPage 확인 및 점검
- [x] 친구추가 클립보드 링크 복사 함수 구현
- ⚠naver state 구현 
- ⚠Header 영역 로그인시 사용자 이름 전환 디벨롭

### 🗓Next Task

- [ ] 다음 할 일1
