### ISSUE TITLE
Scapture 페이지의 video 부분 UI 구현

### ISSUE THREAD

**Issue by xogk1128** [Scapture/Scapture-Client#22]
### ⚠️Issue

- Scapture 페이지의 video 부분 UI를 구현한다.

### ✏️Task

- [x] 영상 프레임 UI 구성
- [x] 날짜 별 리스트 UI 구현
- [x] 해당 날짜의 영상 리스트 UI 구현

### 🗓Next Task

- [ ] 다음 할 일1
- [ ] 다음 할 일2
