### ISSUE TITLE
Scapture 페이지의 구체적 css를 적용 및 검토

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#24]
### ⚠️Issue

- Scapture 페이지의 구체적 css를 적용 및 검토한다.

### ✏️Task

- [x] width, 값과 margin 값을 rem 단위로 적용한다.
- [x] 세부적인 UI의 요소들을 넣는다.
- [x] 해당 페이지를 점검한다.

### 🗓Next Task

- [x] 다음 할 일1
- [x] 다음 할 일2
