### ISSUE TITLE
scss를 설치 및 최종 점검

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#3]
### ⚠️Issue

- scss를 설치한다. root에 디자인 시스템을 적용한다. 단, root의  css는 module 형식이 아니다. 마지막으로 전체 개발 환경 초기 세팅을 점검한다.

### ✏️Task

- [x] module.scss 형식을 학습하고 적용한다.
- [x] scss를 설치한다.
- [x] root에 디자인 시스템을 적용
- [x] 하위 디렉토리에 Scss 폴더 생성 후 파일 적용
- [x] 개발을 위한 dev-terminal 생성 
- [x] 개발 환경 초기 세팅을 점검

### 🗓Next Task

- [x] 각 팀원들이 맡은 페이지 html, css를 적용한다.
