### ISSUE TITLE
API 통신 개발을 위한 세팅

### ISSUE THREAD

**Issue by xogk1128** [Scapture/Scapture-Client#30]
### ⚠️Issue

- 이슈 개요를 입력해 주세요.

### ✏️Task

- [x] 디렉토리 구조 생성
- [x] dotenv를 이용한 보안 문제 해결
- [x] 공통 인터페이스 제작

### 🗓Next Task

- [ ] x
