### ISSUE TITLE
Modal 페이지 점검 및 검토

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#46]
### ⚠️Issue

- Modal 페이지를 검토하고 css를 확인해 본다.

### ✏️Task

- [x] 모든 Modal 페이지를 검토하고 dialog 태그에 id와 className을 적용한다.

### 🗓Next Task

- [x] 페이지를 검토하고 확인해 본다.
- [x] CSS 중점으로 주의사항과 검토를 한다.
