### ISSUE TITLE
Scapture 페이지 구장조회 부분 API 구현

### ISSUE THREAD

**Issue by xogk1128** [Scapture/Scapture-Client#47]
### ⚠️Issue

- Scapture 페이지 구장조회 부분 API를 구현한다.

### ✏️Task

- [x] 도시/지역에 따른 리스트를 보여준다.
- [x] 검색을 통한 리스트를 보여준다.
- [x] 검색 결과에 대한 구장 정보를 보여준다.
- [x] 구장 클릭시 다음 화면으로 넘어가도록 한다.
- [x] 전반적인 CSS를 조정한다.

### 🗓Next Task

- [ ] 다음 할 일1
- [ ] 다음 할 일2
