### ISSUE TITLE
Scapture 페이지 구장 상세조회(Stadium) 부분 API 구현

### ISSUE THREAD

**Issue by xogk1128** [Scapture/Scapture-Client#48]
### ⚠️Issue

- Scapture 페이지 구장 상세조회(Stadium) 부분 API를 구현한다.

### ✏️Task

- [x] 구장 상세 정보 API 통신
- [x] 구장 예약하기 버튼을 통한 페이지 이동
- [x] 날짜를 통한 리스트 조회
- [x] 영상 리스트 조회

### 🗓Next Task

- [ ] x
