### ISSUE TITLE
Scapture 페이지 구장 상세조회(Video) 부분 API 구현

### ISSUE THREAD

**Issue by xogk1128** [Scapture/Scapture-Client#49]
### ⚠️Issue

- Scapture 페이지 구장 상세조회(Video) 부분 API를 구현한다.

### ✏️Task

- [x] 영상 detail 적용하기
- [x] 다운로드 / 공유 / 북마크 구현
- [x] 영상 좋아요 구현
- [x] 날짜에 따른 운영시간 가져오기
- [x] 운영시간에 해당하는 비디오 리스트 가져오기

### 🗓Next Task

- [ ] x
