### ISSUE TITLE
[Test] Moking를 위한 json-server 설치

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#5]
### ⚠️Issue

- Moking를 위한 json-server 설치

### ✏️Task

- [ ] POST를 Moking 하기 위해서 json-server를 설치한다.
- [ ] package.json페이지에 scripts를 커스텀 한다.
- [ ] 직렬이 아닌 병렬로 커스텀을 해본다.

### 🗓Next Task

- [ ] Moking을 시험 해본다.
