### ISSUE TITLE
전체적인 페이지를 검토하고 css를 확인해 본다.

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#53]
### ⚠️Issue

- 페이지를 검토하고 css를 확인해 본다.

### ✏️Task

- [x] 페이지를 검토하고 링크와 모달창을 연결한다.
- [x] 리팩토링이 필요한 페이지를 선별한다.
  - [x] #62
  - [x] #63
- [x] MyPage의 profile 편집 완료 모달 창 구현의 고려를 논의해 본다.
  - [x] '편집 완료' 모달 창을 구현한다.
  - [x] png 파일을 svg로 전환한다.
- [x] develop 브렌치에서 master 브렌치로 merge한다.

### 🗓Next Task

- [x] 다음 할 일1
- [x] 다음 할 일2
