### ISSUE TITLE
MyPage Profile API를 통신한다.

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#55]
### ⚠️Issue

- Profile API를 통신한다.

### ✏️Task

# API
- [x] 프로필 조회(GET)
- [x] 버내너 잔액 조회(GET)
- [x] 예약 내역 조희(GET)
- [x] 프로필 편집(PUT)
- [x] 버내너 충전(POST)
  - [x] 구독 정보 삭제 후 재시도 필요
- [x] 구독 생성(POST)
- [x] 구독 갱신(PUT)
- [x] 저장된 video 조회(GET)
  - [x] 저장된 videos/store?sort=latest 조회(GET)
  - [x] 저장된 videos/store?sort=popularity 조회(GET)

# Atom
- [x] MyPage에 profile 데이터를 담아낼 Atom 생성
  - EidtProfile에서 활용하려 했으나 새로고침 시 발생하는 Atom 데이터 손실로 get 요청 또는 다른 대안, 방안 논의 필요
- [x] MyPage에 banana 데이터를 담아낼 Atom 생성
- [x] MyPage에 subscribe 데이터를 담아낼 Atom 생성
- [x] MyPage에 reservation 데이터를 담아낼 Atom 생성
- [x] ~MyPage에 video 데이터를 담아낼 Atom 생성: ⚠병합 후 검토 필요~

⚠새로고침 시 발생하는 Atom 초기화를 막기위한 Recoil-presist lib 논의 필요
# UI
- [x] API로 부터 ResponseBody로 받은 데이터 배치
- [x] 버내너 충전 값 동적 UI로 구현
- [x] 구독 상황에 따라 달라지는 '구독하기 버튼' 동적 UI로 구현
- [x] 프로필 편집 이름, 소속팀, 활동지역 변경이 가능하게 구현
- [x] 이미지 파일 업로드 구현
- ⚠ 예약 내역 UI 구현
  - [x] 예약 내역 **없음**
  - ⚠ 예약 내역 **있음** : ⚠병합 후 검토 필요
- [x] 비디오 정렬 UI 및 통합 함수 구현
- [x] 저장된 비디오 UI 구현: ⚠병합 후 검토 필요
- [x] 친구초대 URL 자동 복사 구현: ⚠검토 필요

## REQUEST
- [x] 나의 데이터 삭제 필요
- [x] subscribed 데이터 삭제 필요

### 🗓Next Task
- [x] MyPage의 interface를 검토하고 분리한다.
- [x] MyPage의 Atom을 검토하고 분리한다.
- [x] Mypage의 components를 검토하고 분리한다.
- [x] UI 리팩토링 필히 필요
