### ISSUE TITLE
Footer, Header SCSS와 HTML을 구현하다.

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#6]
### ⚠️Issue

- Footer, Header SCSS와 HTML을 구현하다.

### ✏️Task

- [x] Footer, Header SCSS와 HTML을 구현하다.
- [x] 각 페이지에 Footer, Header를 적용한다.

### 🗓Next Task

- [x] Main 페이지 css를 적용한다.
