### ISSUE TITLE
MyPage Profile API를 merge 후 통신 및 점검 한다.

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#80]
### ⚠️Issue

- 이슈 개요를 입력해 주세요.

### ✏️Task

# Atom
- [x] ~MyPage에 video 데이터를 담아낼 Atom 생성: ⚠병합 후 검토 필요~

# UI
- ⚠ 예약 내역 UI 구현
  - [x] 예약 내역 **없음**
  - ⚠ 예약 내역 **있음** : ⚠검토 필요
- [x] 저장된 비디오 UI 구현: ⚠병합 후 검토 필요

### 🗓Next Task

- [ ] 다음 할 일1
- [ ] 다음 할 일2
