### ISSUE TITLE
Modal 페이지 활성화 페이지 점검 및 검토

### ISSUE THREAD

**Issue by 4BFC** [Scapture/Scapture-Client#96]
### ⚠️Issue

- Modal 페이지 활성화 페이지 점검 및 검토

### ✏️Task

- [x] 로그인 상태 값 점검 및 조건 추가
  - [x] 원할하게 동작하지 않음 ⚠초기화 적용 논의 필요
- [x] video 페이지에서 다운로드 클릭 시 로그인 모달 활성화
  - ⚠ api res 기준으로 모달창 활성화
- [x] video 페이지에서 북마크 클릭 시 로그인 모달 활성화
  - ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- [x] video 페이지에서 하트 클릭 시 로그인 모달 활성화
  - ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- [x] reservation 예약하기 클릭 시 로그인 모달 활성화
  - ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- ~community 하트 클릭 시 로그인 모달 활성화~
  - ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화
- ~community 댓글 클릭 시 로그인 모달 활성화~
  - ⚠ video 페이지처럼 기준이 없어서 우선은 클릭으로 모달창 활성화

### 🗓Next Task

- [x] 각 페이지 검토 필요
